apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: result-app
      labels:
        app: my-voting-app
        tier: result
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: my-voting-app
      tier: result
