apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: my-voting-app
        tier: worker
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      app: my-voting-app
      tier: worker
